FROM python:3.9-alpine
WORKDIR /solution

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY req.pip .
RUN pip install -r req.pip --no-cache-dir

COPY . .
RUN \
    chmod +x wait-for-it.sh && \
    apk update && apk add bash