FROM python:3.9-alpine
WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . .
RUN \
    pip install -r req.pip --no-cache-dir && \
    chmod +x wait-for-it.sh && \
    apk update && apk add bash